<?php

namespace Proxies\__CG__\Acme\DemoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \Acme\DemoBundle\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'lastname', 'firstname', 'lastnameCanonical', 'firstnameCanonical', 'birthdate', 'externalId', 'gender', 'language', 'status', 'studentAt', 'student', 'enrolledAt', 'terminatedAt', 'renewedAt', 'insuredAt', 'insured', 'phone', 'mobile', 'email', 'optIn', 'partnerOptin', 'addresses', 'rights', 'payer', 'acceptPartnerCommercial', 'g7crmCode', 'externalReference', 'oldIdContact', 'data', 'externalGuid', 'hash', 'dirty', 'assetBalance', 'pictureName', 'preferentialCode', 'externalNumber', 'createdAt', 'updatedAt');
        }

        return array('__isInitialized__', 'id', 'lastname', 'firstname', 'lastnameCanonical', 'firstnameCanonical', 'birthdate', 'externalId', 'gender', 'language', 'status', 'studentAt', 'student', 'enrolledAt', 'terminatedAt', 'renewedAt', 'insuredAt', 'insured', 'phone', 'mobile', 'email', 'optIn', 'partnerOptin', 'addresses', 'rights', 'payer', 'acceptPartnerCommercial', 'g7crmCode', 'externalReference', 'oldIdContact', 'data', 'externalGuid', 'hash', 'dirty', 'assetBalance', 'pictureName', 'preferentialCode', 'externalNumber', 'createdAt', 'updatedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', array($lastname));

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictureName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictureName', array());

        return parent::getPictureName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPictureName($pictureName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPictureName', array($pictureName));

        return parent::setPictureName($pictureName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', array());

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastnamecanonical($canonicalLastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastnamecanonical', array($canonicalLastname));

        return parent::setLastnamecanonical($canonicalLastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastnamecanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastnamecanonical', array());

        return parent::getLastnamecanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstnamecanonical($canonicalFirstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstnamecanonical', array($canonicalFirstname));

        return parent::setFirstnamecanonical($canonicalFirstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstnamecanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstnamecanonical', array());

        return parent::getFirstnamecanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthdate(\DateTime $birthdate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthdate', array($birthdate));

        return parent::setBirthdate($birthdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthdate', array());

        return parent::getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', array());

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function getHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHash', array());

        return parent::getHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setHash($notUsed = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHash', array($notUsed));

        return parent::setHash($notUsed);
    }

    /**
     * {@inheritDoc}
     */
    public function computeHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'computeHash', array());

        return parent::computeHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalid($externalid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalid', array($externalid));

        return parent::setExternalid($externalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalid', array());

        return parent::getExternalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', array($language));

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', array());

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudentat(\DateTime $studentAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudentat', array($studentAt));

        return parent::setStudentat($studentAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudentat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentat', array());

        return parent::getStudentat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnrolledat(\DateTime $enrolledAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnrolledat', array($enrolledAt));

        return parent::setEnrolledat($enrolledAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnrolledat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnrolledat', array());

        return parent::getEnrolledat();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudent($student)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', array($student));

        return parent::setStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function isStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStudent', array());

        return parent::isStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function addAddresse(\Acme\DemoBundle\Entity\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddresse', array($address));

        return parent::addAddresse($address);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddresse(\Acme\DemoBundle\Entity\Address $addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddresse', array($addresses));

        return parent::removeAddresse($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', array());

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddresses', array($addresses));

        return parent::setAddresses($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultaddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultaddress', array());

        return parent::getDefaultaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayer(\Acme\DemoBundle\Entity\Contact $payer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayer', array($payer));

        return parent::setPayer($payer);
    }

    /**
     * {@inheritDoc}
     */
    public function isPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPayer', array());

        return parent::isPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function getPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayer', array());

        return parent::getPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerminatedat(\DateTime $terminatedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerminatedat', array($terminatedAt));

        return parent::setTerminatedat($terminatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerminatedat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerminatedat', array());

        return parent::getTerminatedat();
    }

    /**
     * {@inheritDoc}
     */
    public function setRenewedat(\DateTime $renewedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRenewedat', array($renewedAt));

        return parent::setRenewedat($renewedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getRenewedat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRenewedat', array());

        return parent::getRenewedat();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuredAt(\DateTime $insuredAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuredAt', array($insuredAt));

        return parent::setInsuredAt($insuredAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuredAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuredAt', array());

        return parent::getInsuredAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsured($insured)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsured', array($insured));

        return parent::setInsured($insured);
    }

    /**
     * {@inheritDoc}
     */
    public function isInsured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInsured', array());

        return parent::isInsured();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptin', array());

        return parent::getOptin();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptin($optIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptin', array($optIn));

        return parent::setOptin($optIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartneroptin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartneroptin', array());

        return parent::getPartneroptin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartneroptin($optIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartneroptin', array($optIn));

        return parent::setPartneroptin($optIn);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcceptPartnerCommercial($acceptPartnerCommercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcceptPartnerCommercial', array($acceptPartnerCommercial));

        return parent::setAcceptPartnerCommercial($acceptPartnerCommercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptPartnerCommercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptPartnerCommercial', array());

        return parent::getAcceptPartnerCommercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setG7crmCode($g7crmCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setG7crmCode', array($g7crmCode));

        return parent::setG7crmCode($g7crmCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getG7crmCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getG7crmCode', array());

        return parent::getG7crmCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalReference($externalReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalReference', array($externalReference));

        return parent::setExternalReference($externalReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalReference', array());

        return parent::getExternalReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldIdContact($oldIdContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldIdContact', array($oldIdContact));

        return parent::setOldIdContact($oldIdContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldIdContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldIdContact', array());

        return parent::getOldIdContact();
    }

    /**
     * {@inheritDoc}
     */
    public function addData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addData', array($data));

        return parent::addData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalGuid($externalGuid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalGuid', array($externalGuid));

        return parent::setExternalGuid($externalGuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalGuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalGuid', array());

        return parent::getExternalGuid();
    }

    /**
     * {@inheritDoc}
     */
    public function isDirty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDirty', array());

        return parent::isDirty();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirty($dirty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirty', array($dirty));

        return parent::setDirty($dirty);
    }

    /**
     * {@inheritDoc}
     */
    public function setAssetbalance($assetBalance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssetbalance', array($assetBalance));

        return parent::setAssetbalance($assetBalance);
    }

    /**
     * {@inheritDoc}
     */
    public function calculateAssetbalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateAssetbalance', array());

        return parent::calculateAssetbalance();
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferentialcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferentialcode', array());

        return parent::getPreferentialcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferentialcode($preferentialCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferentialcode', array($preferentialCode));

        return parent::setPreferentialcode($preferentialCode);
    }

    /**
     * {@inheritDoc}
     */
    public function hasCompletedAffiliatedOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasCompletedAffiliatedOrders', array());

        return parent::hasCompletedAffiliatedOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullContact', array());

        return parent::getFullContact();
    }

    /**
     * {@inheritDoc}
     */
    public function getContactLastnameFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactLastnameFirstname', array());

        return parent::getContactLastnameFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function getCanonicalContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanonicalContact', array());

        return parent::getCanonicalContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalNumber($externalNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalNumber', array($externalNumber));

        return parent::setExternalNumber($externalNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalNumber', array());

        return parent::getExternalNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function addRight(\Acme\DemoBundle\Entity\Right $right)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRight', array($right));

        return parent::addRight($right);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRight(\Acme\DemoBundle\Entity\Right $right)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRight', array($right));

        return parent::removeRight($right);
    }

    /**
     * {@inheritDoc}
     */
    public function getRights()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRights', array());

        return parent::getRights();
    }

}
