parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5432
    database_name:     redpill_dev
    database_fixture_name:     redpill_fixture
    database_user:     eliberty
    database_password: eliberty

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    router.class: Acme\DemoBundle\Router\ApiRouter
    router.request_context.class: Acme\DemoBundle\Router\RequestContext